package com.twu.biblioteca;

import com.twu.biblioteca.book.*;
import com.twu.biblioteca.io.ConsoleInputOutput;
import com.twu.biblioteca.mainmenu.*;
import com.twu.biblioteca.mainmenu.LibrarianMainMenu;
import com.twu.biblioteca.mainmenu.UserMainMenu;
import com.twu.biblioteca.mainmenu.options.*;
import com.twu.biblioteca.movie.AvailableMovie;
import com.twu.biblioteca.movie.Movie;
import com.twu.biblioteca.user.Librarian;
import com.twu.biblioteca.user.User;

import java.util.*;

public class BibliotecaApp {
    public static void main(String []args) {
        Scanner consoleInput = new Scanner(System.in);
        ConsoleInputOutput consoleInputOutput = new ConsoleInputOutput(consoleInput);
        HashSet<User> users = new HashSet<User>();
        User userOne = new User("111-1111", "letmein", "venkatesh", "venkatmk@thoughtworks.com", "9566011847");
        User userTwo = new User("222-2222", "logmein", "chip", "abc@def.com", "9989898989");
        User librarian = new Librarian("333-3333", "superuser", "superman", "super@super.com", "77777777777");
        users.add(userOne);
        users.add(userTwo);
        users.add(librarian);
        Login login = new Login(users, consoleInputOutput);
        Book bookOne = new AvailableBook("java tutorial", "aravind", "2012");
        Book bookTwo = new AvailableBook("Kite Runner", "Khaled Hosseini", "2003");
        Book bookThree = new CheckedOutBook("The Sky Is Falling", "Sidney Sheldon", "2001", userOne);
        LinkedHashSet<BorrowableItem> books = new LinkedHashSet<BorrowableItem>();
        books.add(bookOne);
        books.add(bookTwo);
        books.add(bookThree);
        LinkedHashSet<BorrowableItem> movies = new LinkedHashSet<BorrowableItem>();
        Movie movieOne = new AvailableMovie("Inception", "2010", "Christopher Nolan", "9");
        Movie movieTwo = new AvailableMovie( "Following", "1998", "Christopher Nolan", "8");
        movies.add(movieOne);
        movies.add(movieTwo);
        Library bookLibrary = new Library(books);
        Library movieLibrary = new Library(movies);
        MainMenuAction listBooksOption = new ListBooksOption(consoleInputOutput, bookLibrary);
        HashMap<String, Book> booksTitleToBook = new HashMap<String, Book>();
        booksTitleToBook.put("java tutorial", bookOne);
        booksTitleToBook.put("Kite Runner", bookTwo);
        booksTitleToBook.put("The Sky Is Falling", bookThree);
        CheckoutBookOption checkoutBookOption = new CheckoutBookOption(consoleInputOutput, bookLibrary);
        ReturnBookOption returnBookOption = new ReturnBookOption(consoleInputOutput, bookLibrary);
        MainMenuAction listMoviesOption = new ListMoviesOption(consoleInputOutput, movieLibrary);
        CheckoutMovieOption checkoutMovieOption = new CheckoutMovieOption(consoleInputOutput, movieLibrary);
        ReturnMovieOption returnMovieOption = new ReturnMovieOption(consoleInputOutput, movieLibrary);
        UserInformationOption userInformationOption = new UserInformationOption(consoleInputOutput);
        LinkedHashMap<String, MainMenuAction> options = new LinkedHashMap<String, MainMenuAction>();
        options.put("List Books", listBooksOption);
        options.put("Checkout Book", checkoutBookOption);
        options.put("Return Book", returnBookOption);
        options.put("List Movies", listMoviesOption);
        options.put("Checkout Movie", checkoutMovieOption);
        options.put("Return Movie", returnMovieOption);
        options.put("User Information", userInformationOption);
        Options userOptions = new Options(options);
        LinkedHashMap<String, MainMenuAction> librarianOptionsList = new LinkedHashMap<String, MainMenuAction>();
        librarianOptionsList.put("List Books", listBooksOption);
        librarianOptionsList.put("Checkout Book", checkoutBookOption);
        librarianOptionsList.put("Return Book", returnBookOption);
        librarianOptionsList.put("List Movies", listMoviesOption);
        librarianOptionsList.put("Checkout Movie", checkoutMovieOption);
        librarianOptionsList.put("Return Movie", returnMovieOption);
        librarianOptionsList.put("User Information", userInformationOption);
        MainMenuAction checkedOutBooksOption = new ListCheckedOutBooksOption(consoleInputOutput, bookLibrary);
        librarianOptionsList.put("CheckedOut Books", checkedOutBooksOption);
        MenuPresenter menuPresenter = new MenuPresenter("");
        Options librarianOptions = new Options(librarianOptionsList);
        UserMainMenu userMainMenu = new UserMainMenu(consoleInputOutput, userOptions, menuPresenter);
        LibrarianMainMenu librarianMainMenu = new LibrarianMainMenu(consoleInputOutput, librarianOptions, menuPresenter);
        LinkedHashMap<String, MainMenuAction> guestOptionsList = new LinkedHashMap<String, MainMenuAction>();
        guestOptionsList.put("List Movies", listMoviesOption);
        guestOptionsList.put("List Books", listBooksOption);
        LoginOption loginOption = new LoginOption(login, userMainMenu, librarianMainMenu, consoleInputOutput);
        guestOptionsList.put("Login", loginOption);
        Options guestOptions = new Options(guestOptionsList);
        MainMenu mainMenu = new MainMenu(consoleInputOutput, guestOptions, menuPresenter);
        Biblioteca biblioteca = new Biblioteca(consoleInputOutput, mainMenu, userMainMenu, librarianMainMenu, login);
        biblioteca.start();
    }
}